name: CI/CD to FIREBASE

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}      
    - name: Setup the code
      run: npm install
    - name: Build and Deploy
      run: |
        touch .env
        echo "REACT_APP_API_KEY=${{ secrets.REACT_APP_API_KEY }}" > .env      
        npm run build
        sudo npm install -g firebase-tools@8
        firebase deploy --token ${{ secrets.FIREBASE_TOKEN }} --only hosting        
